// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJDFfofIPtHb_uFaSjGhDx0hAxDJtIDbA',
    appId: '1:933946157522:web:eb75aec187a27b65eb800b',
    messagingSenderId: '933946157522',
    projectId: 'rep-max-6adbe',
    authDomain: 'rep-max-6adbe.firebaseapp.com',
    storageBucket: 'rep-max-6adbe.firebasestorage.app',
    measurementId: 'G-GZN5YF8V5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTVeAFhQ6u5iFqxQuihoom9nDW18PwrIs',
    appId: '1:933946157522:android:394c6101562d6717eb800b',
    messagingSenderId: '933946157522',
    projectId: 'rep-max-6adbe',
    storageBucket: 'rep-max-6adbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJAdQnZm5OUSRauHC3jGJoKWmaLxQwFnw',
    appId: '1:933946157522:ios:153765bb07385240eb800b',
    messagingSenderId: '933946157522',
    projectId: 'rep-max-6adbe',
    storageBucket: 'rep-max-6adbe.firebasestorage.app',
    iosBundleId: 'com.example.repMax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJAdQnZm5OUSRauHC3jGJoKWmaLxQwFnw',
    appId: '1:933946157522:ios:153765bb07385240eb800b',
    messagingSenderId: '933946157522',
    projectId: 'rep-max-6adbe',
    storageBucket: 'rep-max-6adbe.firebasestorage.app',
    iosBundleId: 'com.example.repMax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJDFfofIPtHb_uFaSjGhDx0hAxDJtIDbA',
    appId: '1:933946157522:web:4293ce4a269795d5eb800b',
    messagingSenderId: '933946157522',
    projectId: 'rep-max-6adbe',
    authDomain: 'rep-max-6adbe.firebaseapp.com',
    storageBucket: 'rep-max-6adbe.firebasestorage.app',
    measurementId: 'G-TYYKJLYR7S',
  );

}